export const squareStatus: Record<string | number, string> = {
  SQUARE: "/images/square.png",
  FLAG: "/images/flag.png",
  QUESTION: "/images/question.png",
  BLANK: "/images/blank.png",
  BOMB: "/images/bomb.png",
  BOMBX: "/images/bomb_x.png",
  1: "/images/one.png",
  2: "/images/two.png",
  3: "/images/three.png",
  4: "/images/four.png",
  5: "/images/five.png",
  6: "/images/six.png",
  7: "/images/seven.png",
  8: "/images/eight.png",
};
